-- ARMADA_COMMANDER_START
--NuttyB v1.52c Armada Com
{
  armcom = {
    footprintx = 2,
    footprintz = 2,
    customparams = {
      evolution_target = 'armcomlvl2',
      evolution_condition = 'timer_global',
      evolution_timer = 420,
    },
    energymake = 100,
    metalmake = 10,
    autoheal = 55,
    health = 4500,
    speed = 41,
    canresurrect = true,
    buildoptions = {
      'armsolar',
      'armwin',
      'armmstor',
      'armestor',
      'armmex',
      'armmakr',
      'armgate',
      'armlab',
      'armnanotc',
      'armvp',
      'armap',
      'armeyes',
      'armrad',
      'armdrag',
      'armllt',
      'armrl',
      'armdl',
      'armtide',
      'armuwms',
      'armuwes',
      'armuwmex',
      'armfmkr',
      'armsy',
      'armfdrag',
      'armtl',
      'armfrt',
      'armfrad',
      'armhp',
      'armfhp',
      'armgeo',
      'armamex',
      'armbeamer',
      'armjamt',
      'armsy',
      'armrectr',
      'armclaw',
    },
    weapondefs = {
      armcomlaser = {
        range = 330,
        rgbcolor = '0.7 1 1',
        soundstart = 'lasrfir1',
        damage = {
          default = 175,
        },
      },
      old_armsnipe_weapon = {
        areaofeffect = 32,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 0.85,
        energypershot = 400,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 0.8,
        name = 'Long-range rail rifle',
        range = 550,
        reloadtime = 1,
        rgbcolor = '0 1 1',
        rgbcolor2 = '0 1 1',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 7,
        customparams = {
          stockpilelimit = 5,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 4,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 100,
          default = 4900,
        },
      },
    },
    weapons = {
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
    },
  },
  armcomlvl2 = {
    footprintx = 2,
    footprintz = 2,
    autoheal = 125,
    builddistance = 200,
    canresurrect = true,
    energymake = 315,
    health = 8125,
    speed = 57.5,
    metalmake = 30,
    workertime = 1700,
    buildoptions = {
      'armsolar',
      'armwin',
      'armmstor',
      'armestor',
      'armmex',
      'armmakr',
      'armgate',
      'armlab',
      'armvp',
      'armap',
      'armeyes',
      'armrad',
      'armdrag',
      'armllt',
      'armrl',
      'armdl',
      'armtide',
      'armuwms',
      'armuwes',
      'armuwmex',
      'armfmkr',
      'armsy',
      'armfdrag',
      'armtl',
      'armfrt',
      'armfrad',
      'armhp',
      'armfhp',
      'armadvsol',
      'armgeo',
      'armamex',
      'armlwall',
      'armnanotct2',
      'armclaw',
      'armbeamer',
      'armhlt',
      'armguard',
      'armferret',
      'armcir',
      'armjamt',
      'armjuno',
      'armsy',
      'armrectr',
    },
    customparams = {
      evolution_target = 'armcomlvl3',
      evolution_condition = 'timer_global',
      evolution_timer = 1320,
    },
    weapondefs = {
      armcomlaser = {
        areaofeffect = 16,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 425,
        reloadtime = 0.7,
        rgbcolor = '0 1 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrfir1',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 4,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 950,
          VTOL = 150,
        },
      },
      old_armsnipe_weapon = {
        areaofeffect = 42,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 0.85,
        energypershot = 700,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 1,
        name = 'Long-range g2g armor-piercing rifle',
        range = 700,
        reloadtime = 1,
        rgbcolor = '0.2 0.1 1',
        rgbcolor2 = '0.2 0.1 1',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 6,
        customparams = {
          stockpilelimit = 10,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 4,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 10,
          default = 11000,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
    },
  },
  armcomlvl3 = {
    footprintx = 2,
    footprintz = 2,
    autoheal = 600,
    builddistance = 350,
    canresurrect = true,
    energymake = 2712,
    health = 16000,
    speed = 71.5,
    metalmake = 62,
    workertime = 3400,
    buildoptions = {
      'armanni',
      'armpb',
      'armamb',
      'armmoho',
      'armuwmme',
      'armflak',
      'armmercury',
      'armgate',
      'armsd',
      'armfort',
      'armtarg',
      'armarad',
      'armamd',
      'armveil',
      'armuwadvms',
      'armuwadves',
      'armmmkr',
      'armuwmmm',
      'armavp',
      'armaap',
      'armalab',
      'armfflak',
      'armatl',
      'armkraken',
      'armbrtha',
      'armannit3',
      'armlwall',
      'armgatet3',
      'armannit4',
      'armnanotct2',
      'armnanotct3',
    },
    customparams = {
      evolution_target = 'armcomlvl4',
      evolution_condition = 'timer_global',
      evolution_timer = 1740,
    },
    weapondefs = {
      old_armsnipe_weapon = {
        areaofeffect = 64,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 1,
        energypershot = 2000,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 1.4,
        name = 'Long-range g2g armor-piercing rifle',
        range = 1250,
        reloadtime = 0.5,
        rgbcolor = '0.4 0.1 0.7',
        rgbcolor2 = '0.4 0.1 0.7',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 3,
        customparams = {
          stockpilelimit = 10,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 6,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 10,
          default = 35000,
        },
      },
      armcomlaser = {
        areaofeffect = 12,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 500,
        reloadtime = 0.6,
        rgbcolor = '0.1 0 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw2',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 6,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 1450,
          VTOL = 180,
        },
      },
    },
    weapons = {
      [5] = {
        badtargetcategory = 'MOBILE',
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
      [4] = {
        def = '',
      },
      [1] = {
        def = '',
      },
      [6] = {
        def = '',
      },
    },
  },
  armcomlvl4 = {
    footprintx = 2,
    footprintz = 2,
    autoheal = 2213,
    builddistance = 500,
    canresurrect = true,
    energymake = 3112,
    health = 28000,
    speed = 82,
    metalmake = 86,
    workertime = 6200,
    buildoptions = {
      'armanni',
      'armpb',
      'armamb',
      'armmoho',
      'armuwmme',
      'armflak',
      'armmercury',
      'armgate',
      'armsd',
      'armfort',
      'armtarg',
      'armarad',
      'armamd',
      'armveil',
      'armuwadvms',
      'armuwadves',
      'armmmkr',
      'armuwmmm',
      'armavp',
      'armaap',
      'armalab',
      'armfflak',
      'armatl',
      'armkraken',
      'armbrtha',
      'armannit3',
      'armlwall',
      'armgatet3',
	    'armannit4',
	    'armnanotct3',
    },
    weapondefs = {
      old_armsnipe_weapon = {
        areaofeffect = 72,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 1,
        energypershot = 2000,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 1.4,
        name = 'Long-range g2g armor-piercing rifle',
        range = 1250,
        reloadtime = 0.5,
        rgbcolor = '0.4 0.1 0.7',
        rgbcolor2 = '0.4 0.1 0.7',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 2,
        customparams = {
          stockpilelimit = 15,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 6,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 10,
          default = 45000,
        },
      },
      ata = {
        areaofeffect = 16,
        avoidfeature = false,
        beamtime = 1.25,
        collidefriendly = false,
        corethickness = 0.5,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        edgeeffectiveness = 0.30,
        energypershot = 7000,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 90,
        impulsefactor = 0,
        largebeamlaser = true,
        laserflaresize = 7,
        name = 'Heavy tachyon beam',
        noselfdamage = true,
        range = 1100,
        reloadtime = 15,
        rgbcolor = '1 0 1',
        scrollspeed = 5,
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'annigun1',
        soundtrigger = 1,
        texture3 = 'largebeam',
        thickness = 10,
        tilelength = 150,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 3100,
        damage = {
          commanders = 480,
          default = 48000,
        },
      },
      armcomlaser = {
        areaofeffect = 12,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Close-range laser',
        noselfdamage = true,
        range = 550,
        reloadtime = 0.5,
        rgbcolor = '0.659 0 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw2',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 6,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 1750,
          VTOL = 200,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
      [4] = {
        badtargetcategory = 'VTOL GROUNDSCOUT',
        def = 'ATA',
        onlytargetcategory = 'SURFACE',
      },
      [5] = {
        def = '',
      },
      [6] = {
        def = '',
      },
    },
  },
}
-- ARMADA_COMMANDER_END
